import {
  //   SHOW_NEW_NUGGETS_STATE,
  //   UPDATE_NEW_NUGGETS_STATE,
  NEW_NUGGETS_ERROR_MESSAGE,
  POST_NEW_NUGGETS_REQUEST,
  POST_NEW_NUGGETS_SUCCESS
  //   RESET_NEW_NUGGETS_STATE,
  //   DELETE_NUGGETS_REQUEST,
  //   DELETE_NUGGETS_ERROR,
  //   DELETE_NUGGETS_SUCCESS
} from "../actions/Nuggets";
